# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eP_tnAe6BDgtCERnPvtx48yHI9K8HF4w
"""

import pandas as pd
df =pd.DataFrame({ 'ism':['Muhammadsher', 'SHohruh','Mardonbek'],
                  'Familya':['isakjonov', 'Zaynobiddinov', 'Tursunov', ],
                  'Yoshi':['18','19','20'],
                  'Kursi':['2','3','4']
})
print(df)